import './globals.css'
import {Rubik} from 'next/font/google'
import Navigation from "@/app/components/Navigation";
import DownloadButton from "@/app/components/DownloadButton";

const rubik = Rubik({subsets: ['latin']})

export const metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={rubik.className}>
            <div className="text-white pl-5 pr-5 md:pl-20 md:pr-20 pt-5 md:pt-10 flex flex-col min-h-screen bg-grey-300 relative">
                <div className="bg-gray-800 items-center flex flex-col rounded-t-3xl p-5 md:p-10 flex-1">
                    <h1>Marina Savelieva CV</h1>
                    <Navigation/>
                    {children}
                </div>
            </div>
            <DownloadButton/>
        </body>
        </html>
    )
}
